name: Application CI/CD 

on:
  push:
    branches: [ "main" ]

env:
  GITHUB_REPO: REPOAPPLICATION

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      # Build Docker image and push it to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ${DOCKER_USERNAME}/my-app:latest -f ${GITHUB_REPO}/Dockerfile .
          docker push ${DOCKER_USERNAME}/my-app:latest
